# Generated by Django 5.1.3 on 2024-11-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abrigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('responsavel', models.CharField(max_length=200)),
                ('capacidade', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Abrigo',
                'verbose_name_plural': 'Abrigos',
            },
        ),
    ]
